"""empty message

Revision ID: 07ed06b6293c
Revises: 
Create Date: 2022-09-26 21:24:41.504562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ed06b6293c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('account', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('account', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('belong', sa.String(length=40), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('store_class', sa.String(length=200), nullable=False),
    sa.Column('cookies', sa.String(length=2000), nullable=False),
    sa.Column('grade_before', sa.Float(), nullable=True),
    sa.Column('grade_now', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['belong'], ['worker.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookies'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('cost_total',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_uuid', sa.String(length=40), nullable=False),
    sa.Column('time_belong', sa.Date(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['store_uuid'], ['store.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_total',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turnover_target', sa.Float(), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=False),
    sa.Column('turnover_rate', sa.Float(), nullable=False),
    sa.Column('income_target', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('income_rate', sa.Float(), nullable=False),
    sa.Column('order_num_target', sa.Float(), nullable=False),
    sa.Column('order_num', sa.Float(), nullable=False),
    sa.Column('order_num_rate', sa.Float(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('store_uuid', sa.String(length=40), nullable=False),
    sa.Column('time_belong', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['store_uuid'], ['store.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_per_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost_total_uuid', sa.String(length=40), nullable=False),
    sa.Column('time_belong', sa.Date(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cost_total_uuid'], ['cost_total.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_per_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turnover_target', sa.Float(), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=False),
    sa.Column('turnover_rate', sa.Float(), nullable=False),
    sa.Column('income_target', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('income_rate', sa.Float(), nullable=False),
    sa.Column('order_num_target', sa.Float(), nullable=False),
    sa.Column('order_num', sa.Float(), nullable=False),
    sa.Column('order_num_rate', sa.Float(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('kpi_total_uuid', sa.String(length=40), nullable=False),
    sa.Column('time_belong', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_total_uuid'], ['kpi_total.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_per_day')
    op.drop_table('cost_per_day')
    op.drop_table('kpi_total')
    op.drop_table('cost_total')
    op.drop_table('store')
    op.drop_table('worker')
    op.drop_table('manager')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
